name: PyPI Release

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Set package version from tag
      run: |
        echo "Tag name from github.ref_name: ${{  github.ref_name }}"
        sed -i "s/VERSION = 'TAG'/VERSION = '${{ github.ref_name }}'/" setup.py

    - name: Build package
      run: python -m build

    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_PYTFC_API_TOKEN }}