name: Test PyPI CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run pytest
      run: |
          pytest tests/
      env:
          TFE_TOKEN: ${{ secrets.PYTEST_TFE_TOKEN }}
          TFE_GHAIN: ${{ secrets.PYTEST_TFE_GHAIN }}

  build_and_release:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Tag check
        id: tagCheck
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::set-output name=isTag::true"
          else
            echo "::set-output name=isTag::false"
          fi
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Set version
        if: steps.tagCheck.outputs.isTag == 'true'
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          sed -i "s/VERSION = 'TAG'/VERSION = '${{ github.ref_name }}'/" setup.py
      
      - name: Build package
        run: python -m build
    
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PYTFC_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/