name: Test PyPI CI

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Run pytest
      run: |
          pytest tests/
      env:
          TFE_TOKEN: ${{ secrets.PYTEST_TFE_TOKEN }}
          TFE_GHAIN: ${{ secrets.PYTEST_TFE_GHAIN }}

  build_and_release:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Tag check
        id: tag_check
        run: |
          if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-test$ ]]; then
            echo "{is_tag}={true}" >> $GITHUB_OUTPUT
          else
            echo "{is_tag}={false}" >> $GITHUB_OUTPUT
          fi

      - name: Set version from tag
        if: steps.tag_check.outputs.is_tag == 'true'
        run: |
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          sed -i "s/VERSION = 'TAG'/VERSION = '${{ github.ref_name }}'/" setup.py
      
      - name: Set version from run number
        if: steps.tag_check.outputs.is_tag == 'false'
        run: |
          VERSION_PREFIX="v0.0."
          NEW_VERSION="$VERSION_PREFIX${{ github.run_number }}"
          echo "$NEW_VERSION"
          sed -i "s/VERSION = 'TAG'/VERSION = '$NEW_VERSION'/" setup.py

      - name: Build package
        run: python -m build
    
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PYTFC_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/